#############################################################################
# MULTI-STABS FULL MODEL
#
# THIS SCRIPT SPECIFIES THE ENTIRE MODEL INCLUDING ITS SUB-MODELS
# 

#############################################################################  

# set wd to location of current file
  # setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
  
# this script is dependant on the model_params script (scenario scripts)
# without it the current script does not work
  
  pacman::p_load(ggplot2, dplyr, patchwork)
  # set.seed(100)
  
  
  #could use any real first date and it should run
  time_zero_date<-as.Date("2018-01-01")
  
  
  #simulate the full epidemic for up to 2 years
  max_t<-365*2
  
  #this just saves the times
  num_years<-5
  curr_year<-as.numeric(format(time_zero_date, format="%Y"))
  curr_month<-as.numeric(format(time_zero_date, format="%m"))
  the_season<-curr_month
  the_year<-curr_year
  
  mydates<-data.frame(matrix(NA,nrow=(num_years*12),ncol=2))
  names(mydates)<-c("days_until_rate_change","month")
  month_formating<-c("-01","-02","-03","-04","-05","-06","-07","-08","-09","-10","-11","-12")
  for(ii in 0:(num_years-1)){
    for(jj in 0:11){
      mydates[(jj+1)+12*ii,1]<-as.Date(paste(as.character(the_year),month_formating[(jj+curr_month-1)%%12+1],"-01",sep=""))-time_zero_date
      mydates[(jj+1)+12*ii,2]<-(jj+curr_month-1)%%12+1
      if(mydates[(jj+1)+12*ii,2]==12){
        the_year<-the_year+1
      }
    }
  }
  
  #this returns the relevant row from the matrix of dates (relating to month changes) given a time (in days)
  current_daymonth<-function(time_from_current_date){
    past_dates<-which(mydates$days_until_rate_change<=time_from_current_date)
    if(length(past_dates)==0){
      current_row<-length(mydates[,1])
    }else{
      current_row<-past_dates[length(past_dates)]
    }
    return(current_row)
  }
  
  #this generates the next time that a mosquito is generated by an individual (inhomogeneous poisson process for seasonal model)
  mozzy_generation_times<-function(t,new_mozzys,tG){
    
    the_season_row<-current_daymonth(t)
    the_season<-mydates$month[the_season_row]
    the1st<-mydates$days_until_rate_change[the_season_row]
    t_delta<-rexp(1,rate=new_mozzys[the_season])
    newt_season_row<-current_daymonth(t2+t_delta)
    newt_1st<-mydates$days_until_rate_change[newt_season_row]
    
    while(newt_1st!=the1st & (the1st)<min(tG,max_t, na.rm = TRUE)){ #the na.rm is not needed, but can help
      the_season_row<-the_season_row+1
      the_season<-mydates$month[the_season_row]
      the1st<-mydates$days_until_rate_change[the_season_row]
      t_delta<-the1st-t+rexp(1,rate=new_mozzys[the_season])
      newt_season_row<-current_daymonth(t2+t_delta)
      newt_1st<-mydates$days_until_rate_change[newt_season_row]
    }
    
    return(t_delta)
  }
  
  
  #need an adjacency matrix of distances.
  Distances<-matrix(NA,nrow=length(hh_labels),ncol=length(hh_labels))
  for(ii in 1:length(hh_labels)){
    Distances[,ii]<-((people_locations[ii,1]-people_locations[,1])^2+(people_locations[ii,2]-people_locations[,2])^2)^(1/2)
    Distances[ii,ii]<-0
  }
  
  max_stack_h<-10000
  max_stack_m<-300000
  #Human data frame (saves times of exposure infectiousness and recovery)
  human_stack<-data.frame(matrix(NA,nrow=max_stack_h,ncol=9))
  names(human_stack)<-c("hh_id","ind_id","t", "mal_species_t", "Pf_state_prev", "Pf_state_current",
                        "Pv_state_prev","Pv_state_current","df_index")
  
  #mosquito stack saves newly infected mosquitos and the transitions through their life (from the time of infection)
  mosquito_stack<-data.frame(matrix(NA,nrow=max_stack_m,ncol=6))
  names(mosquito_stack)<-c("mosquito_id","t","event", "mal_species", "infectious_status","hh_id")
  
  # # exposure times
  # tE=matrix(NA,nrow=max_stack_h,ncol=1)
  
  #infectiousness times
  tI_in=matrix(NA,nrow=max_stack_h,ncol=1) 
  tI_out=matrix(NA,nrow=max_stack_h,ncol=1) 
  
  #radical cure treatment times
  tG=matrix(NA,nrow=max_stack_h,ncol=1)
  
  #standard cure treatment times
  tT=matrix(NA,nrow=max_stack_h,ncol=1)
  
  #entry of latent stage times
  tL=matrix(NA,nrow=max_stack_h,ncol=1)
  
  #loss of immunity times
  tS=matrix(NA,nrow=max_stack_h,ncol=1)
  
  #the possible infection stack is all that is needed to generate realisations of the infection process (without saving all of the mosqito level events)
  #events in the stack will cause an infection in humans in the relative household with probability S/N
  possible_infection_stack<-data.frame(matrix(NA,nrow=max_stack_h,ncol=4))
  names(possible_infection_stack)<-c("hh_id","ind_id","t", "mal_species")
  exposure_time<-matrix(NA,nrow=max_stack_h,ncol=1)
  temp_death_time<-matrix(NA,nrow=max_stack_h,ncol=1)
  stack_size<-0
  inf_stack_size<-0
  L_relapse_count<-0
  
  #mosquito count
  m_count<-0
  
  #time/counter
  t<-0
  
  
  #the sick people (with plasmodium falciparum)
  sick_puppies_pf<-which(ind_level_data$malaria==1) # sick_puppies are row IDs
  # for plasmodium malariae:
  sick_puppies_pm<-which(ind_level_data$malaria==2)
  # for plasmodium vivax:
  sick_puppies_pv<-which(ind_level_data$malaria==3)
  # all sick people: (careful malaria type is mixed, not stacked here)
  sick_puppies <- which(ind_level_data$malaria==1 | ind_level_data$malaria==3) # we're not considering P. malariae atm (because interactions not well known)
  
  #the number of events on the stack for humans (just to keep track of all of the events)
  h_stack_count<-0;
  
  
  human_state<-matrix(0,nrow=length(ind_level_data$hh_id),ncol=1)
  human_state[sick_puppies_pf]<-1
  human_state[sick_puppies_pm]<-2
  human_state[sick_puppies_pv]<-3
  initial_I_pf<-length(sick_puppies_pf)
  initial_I_pm<-length(sick_puppies_pm)
  initial_I_pv<-length(sick_puppies_pv)
  # total malaria initial I:
  initial_I <- length(sick_puppies)
  
  # total number of human individuals in the system (for susceptibility graphs)
  tot_h <- nrow(ind_level_data)
  # total number of households in system
  tot_hh <- length(unique(ind_level_data$hh_id))
  
  spec_names <- c("Pf", "Pm", "Pv")
  
  
  #state indicators:
  # 0 -> S
  # 1 -> E
  # 2 -> I
  # 3 -> A
  # 4 -> G
  # 5 -> T
  # 6 -> L
  
  #initial recovery times
  #of humans
  
  # putting all initially infected people through the model until they are susceptible again
  # and generating infected mosquitos from all of them--------------------------
  # INITAL TRANSITION LOOP #
  for( jj in 1:length(sick_puppies)){  # for each of the sick individuals (I) row IDs
      h_stack_count<-h_stack_count+1
      temp_first_count <- h_stack_count
      
      human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[sick_puppies[jj]] # updating household ID to the household ID of the current sick person
      human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[sick_puppies[jj]]
      human_stack$df_index[h_stack_count]<-sick_puppies[jj] #
      temp_mal_species <- ind_level_data$malaria[sick_puppies[jj]]
      human_stack$mal_species_t[h_stack_count] <- temp_mal_species
      
      tI_in[h_stack_count]<-0
 
      rand_treat <- runif(1) # drawing a random number to decide whether the ind gets treated or not
      # if the species is vivax
      if(temp_mal_species == 3){ 
        # setting the states of the other malaria species to 0
        human_stack$Pf_state_prev[h_stack_count]<- 0
        human_stack$Pf_state_current[h_stack_count]<- 0
        
        human_stack$Pv_state_prev[h_stack_count]<- 2 # 2 is I

        if(rand_treat < treat_prob){ # if they get treated
          rand_cure <- runif(1)
          if(rand_cure < cure_prob){ # if they get radical cure (prob for standard cure is 1-cure_prob)
            # record treatment (beginning of radical cure treatment)
            tI_out[h_stack_count]<- tI_in[h_stack_count]+rexp(1,rate=treat_speed) 
            human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
            tG[h_stack_count]<-human_stack$t[h_stack_count]
            human_stack$Pv_state_current[h_stack_count]<- 4 # 4 is G

            # record loss of immunity (end of radical cure treatment)
            h_stack_count<-h_stack_count+1
            human_stack$t[h_stack_count] <- human_stack$t[h_stack_count-1] + dur_RC
            human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[sick_puppies[jj]] # updating household ID to the household ID of the current sick person
            human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[sick_puppies[jj]]
            human_stack$df_index[h_stack_count]<-sick_puppies[jj] #
            human_stack$mal_species_t[h_stack_count] <- temp_mal_species
            
            human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
            human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
            human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
            human_stack$Pv_state_current[h_stack_count]<- 0 # 0 is S
            tS[h_stack_count]<-human_stack$t[h_stack_count]
            
          }else{ # standard cure
            # record treatment (beginning of standard cure treatment)
            tI_out[h_stack_count]<-tI_in[h_stack_count]+rexp(1,rate=treat_speed) 
            human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
            tT[h_stack_count]<-human_stack$t[h_stack_count]
            human_stack$Pv_state_current[h_stack_count]<- 5 # 5 is T
            
            rand_LvT <- runif(1)
            if(rand_LvT < LvT_prob){ # if they develop hypnozoites after standard cure treatment
              # record latent event
              h_stack_count<-h_stack_count+1
              human_stack$t[h_stack_count] <- human_stack$t[h_stack_count-1] + dur_SC
              human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[sick_puppies[jj]] # updating household ID to the household ID of the current sick person
              human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[sick_puppies[jj]]
              human_stack$df_index[h_stack_count]<-sick_puppies[jj] #
              human_stack$mal_species_t[h_stack_count] <- temp_mal_species
              
              human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
              human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
              human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
              human_stack$Pv_state_current[h_stack_count]<- 6 # 6 is L
              tL[h_stack_count]<-human_stack$t[h_stack_count]

              # record recovery  (abbau von hynozoites)
              h_stack_count<-h_stack_count+1
              human_stack$t[h_stack_count] <- human_stack$t[h_stack_count-1] + rexp(1,rate=no_hypno)
              human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[sick_puppies[jj]] # updating household ID to the household ID of the current sick person
              human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[sick_puppies[jj]]
              human_stack$df_index[h_stack_count]<-sick_puppies[jj] #
              human_stack$mal_species_t[h_stack_count] <- temp_mal_species
              
              human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
              human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
              human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
              human_stack$Pv_state_current[h_stack_count]<- 0 # 0 is S
              tS[h_stack_count]<-human_stack$t[h_stack_count]
              
            }else{ # no hypnozoites after standard cure
              # record recovery
              h_stack_count<-h_stack_count+1
              human_stack$t[h_stack_count] <- human_stack$t[h_stack_count-1] + dur_SC
              human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[sick_puppies[jj]] # updating household ID to the household ID of the current sick person
              human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[sick_puppies[jj]]
              human_stack$df_index[h_stack_count]<-sick_puppies[jj] #
              human_stack$mal_species_t[h_stack_count] <- temp_mal_species
              
              human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
              human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
              human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
              human_stack$Pv_state_current[h_stack_count]<- 0 # 0 is S
              tS[h_stack_count]<-human_stack$t[h_stack_count]
              
            }
          }
          
        }else{ # no treatment
          rand_Lv <- runif(1)
          if(rand_Lv < Lv_prob){ #hypnozoites after no treatment
            # record latent event
            tI_out[h_stack_count]<-tI_in[h_stack_count]+rexp(1,rate=Ldev_rate) 
            human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
            tL[h_stack_count]<-human_stack$t[h_stack_count]
            human_stack$Pv_state_current[h_stack_count]<- 6 # 6 is L
            
            # record recovery (decay von hynozoites)
            h_stack_count<-h_stack_count+1
            human_stack$t[h_stack_count] <- human_stack$t[h_stack_count-1] + rexp(1,rate=no_hypno)
            human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[sick_puppies[jj]] # updating household ID to the household ID of the current sick person
            human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[sick_puppies[jj]]
            human_stack$df_index[h_stack_count]<-sick_puppies[jj] #
            human_stack$mal_species_t[h_stack_count] <- temp_mal_species
            
            human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
            human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
            human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
            human_stack$Pv_state_current[h_stack_count]<- 0 # 0 is S
            tS[h_stack_count]<-human_stack$t[h_stack_count]
            
          }else{ #no hypnozoites after no treatment
            tI_out[h_stack_count]<-tI_in[h_stack_count]+rexp(1,rate=gammaH) # everybody who is already infectious will be treated by this time (defined by recovery rate gammaH)
            human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
            tS[h_stack_count]<-human_stack$t[h_stack_count]
            human_stack$Pv_state_current[h_stack_count]<- 0 # 0 is S
            
          }
        }

        
      }else{ # if not vivax (i.e. if falciparum)
           # setting the states of the other malaria species to 0
           human_stack$Pv_state_prev[h_stack_count]<- 0
           human_stack$Pv_state_current[h_stack_count]<- 0
           
           human_stack$Pf_state_prev[h_stack_count]<- 2 # 2 is I
           
           if(rand_treat < treat_prob){ # if they get treated
             rand_cure <- runif(1)
             if(rand_cure < cure_prob){ # if they get radical cure (prob for standard cure is 1-cure_prob)
               # record treatment (beginning of radical cure treatment)
               tI_out[h_stack_count]<-tI_in[h_stack_count]+rexp(1,rate=treat_speed) 
               human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
               tG[h_stack_count]<-human_stack$t[h_stack_count]
               human_stack$Pf_state_current[h_stack_count]<- 4 # 4 is G
               
               # record loss of immunity (end of radical cure treatment)
               h_stack_count<-h_stack_count+1
               human_stack$t[h_stack_count] <- human_stack$t[h_stack_count-1] + dur_RC
               human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[sick_puppies[jj]] # updating household ID to the household ID of the current sick person
               human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[sick_puppies[jj]]
               human_stack$df_index[h_stack_count]<-sick_puppies[jj] #
               human_stack$mal_species_t[h_stack_count] <- temp_mal_species
               
               human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
               human_stack$Pv_state_current[h_stack_count]<- human_stack$Pv_state_prev[h_stack_count] # no change in Pv
               human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
               human_stack$Pf_state_current[h_stack_count]<- 0 # 0 is S
               tS[h_stack_count]<-human_stack$t[h_stack_count]
               
             }else{ # standard cure
               # record treatment (beginning of standard cure treatment)
               tI_out[h_stack_count]<-tI_in[h_stack_count]+rexp(1,rate=treat_speed) 
               human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
               tT[h_stack_count]<-human_stack$t[h_stack_count]
               human_stack$Pf_state_current[h_stack_count]<- 5 # 5 is T

                 # record recovery/loss of immunity (end of standard cure treatment)
                 h_stack_count<-h_stack_count+1
                 human_stack$t[h_stack_count] <- human_stack$t[h_stack_count-1] + dur_SC
                 human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[sick_puppies[jj]] # updating household ID to the household ID of the current sick person
                 human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[sick_puppies[jj]]
                 human_stack$df_index[h_stack_count]<-sick_puppies[jj] #
                 human_stack$mal_species_t[h_stack_count] <- temp_mal_species
                 
                 human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
                 human_stack$Pv_state_current[h_stack_count]<- human_stack$Pv_state_prev[h_stack_count] # no change in Pv
                 human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
                 human_stack$Pf_state_current[h_stack_count]<- 0 # 0 is S
                 tS[h_stack_count]<-human_stack$t[h_stack_count]
    
             }
           }else{ # no treatment
             tI_out[h_stack_count]<-tI_in[h_stack_count]+rexp(1,rate=gammaH) # everybody who is already infectious will be treated by this time (defined by recovery rate gammaH)
             human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
             tS[h_stack_count]<-human_stack$t[h_stack_count]
             human_stack$Pf_state_current[h_stack_count]<- 0 # 0 is S
             }
         }

      # creating the new mosquitos with respect to their seasonal probability
      new_mozzys<-seasonal_creation[sick_puppies[jj],]
      
      ##--------------------------------------------------
      #generate all mosquitos from the existing sick people
      
      
      # get the start and end times of the infectiousness periods of the current human individual
      temp_ind_tI <- as.data.frame(cbind(temp_first_count:h_stack_count, 
                           tI_in[temp_first_count:h_stack_count],
                           tI_out[temp_first_count:h_stack_count]))
      temp_ind_tI <- temp_ind_tI[complete.cases(temp_ind_tI),]
      
      for (kk in 1:nrow(temp_ind_tI)) {
        t2<-temp_ind_tI[kk, 2]
        t3<-temp_ind_tI[kk, 3]
    

      t_delta<-mozzy_generation_times(t2,new_mozzys,t3) 
      # t_delta<-mozzy_generation_times(tI_in,new_mozzys,tI_out)
    
      while((t2+t_delta)<min(t3,max_t)){
        #generate/record time of event
        
        t2<-t2+t_delta
        
        #generate a mosquito into the relevant household
        ind_moz_index<-sick_puppies[jj]
        

        # Malaria mosquito activity is independent of the state of the system, 
        # assuming a fixed treatment of households over their
        # lifetime (the impact on infection is state dependent though)
        m_count<-m_count+1
        
        #currently let all mosquitoes be introduced as full (maybe change this later). 
        # 1: hungry, 2: full, 3: dead, hh_id: travelling to hh_id
        
        # now to add the mosquitoes movements to the stack
        # THESE CAN BE CHANGED TO NOT BE EXPONENTIAL
        temp_infectious_time<-t2+rexp(1,rate=sigmaM) # the time from when infectiousness begins
        exposure_time[m_count]<-temp_infectious_time
        temp_death_time[m_count]<-t2+rexp(1,rate=death_rate)
        
        
        mozzy_id<-m_count
        temp_hh<-ind_level_data$hh_id[ind_moz_index]
        temp_mozzy_hh_index<-which(hh_labels==temp_hh)
        temp_t<-t2
        temp_state<-2 ###THIS COULD BE CHANGED LATER
        temp_infectious_state<-0
        
        stack_size<-stack_size+1
        mosquito_stack$mosquito_id[stack_size]<-mozzy_id
        mosquito_stack$hh_id[stack_size]<-temp_hh
        mosquito_stack$t[stack_size]<-temp_t
        mosquito_stack$event[stack_size]<-temp_state
        mosquito_stack$infectious_status[stack_size]<-temp_infectious_state
        mosquito_stack$mal_species[stack_size] <- temp_mal_species
        
        while(temp_t<temp_death_time[m_count] & temp_state!=3 & temp_t<max_t){
          
          
          #If the mosquito is hungry it bites
          if(temp_state==1){
            # if hungry bite and stay hungry, bite and get full or bite+die
            temp_t<-temp_t+rexp(1,rate=bite_rate)
            rand_event=runif(1)
            if(rand_event<multiple_meal){
              #bite and not full
              temp_state<-1
            }else if(rand_event<(multiple_meal+(1-multiple_meal)*(1-hh_deathonbite[temp_mozzy_hh_index]))){
              #full
              temp_state<-2
            }else{
              #dead on bite
              temp_state<-3
            }
            
            #generates effective contact between an infectious mosquito and a human
            if(temp_t>temp_infectious_time & temp_t<temp_death_time[m_count] & temp_t<max_t){
              rand_inf=runif(1)
              if(rand_inf<transMH_per_bite){
                inf_stack_size<-inf_stack_size+1
                possible_infection_stack$hh_id[inf_stack_size]<-temp_hh
                possible_infection_stack$t[inf_stack_size]<-temp_t
                possible_infection_stack$ind_id[inf_stack_size]<-ceiling(runif(1)*N[temp_mozzy_hh_index])
                possible_infection_stack$mal_species[inf_stack_size] <- temp_mal_species
              }
            }
            
            #If the mosquito is full it moves after a holding time
          }else if(temp_state==2){
            
            #generate time that the mosquito will be ready to travel
            temp_t<-temp_t+rexp(1,rate=Mfull)
            
            the_season<-mydates$month[ current_daymonth(temp_t)]
            
            #the mosquitos choice of new hh
            hhprobs<-(scaled_seasonal_MAP[,the_season]*hh_bite_prop)*(pnorm(Distances[,temp_mozzy_hh_index],0,10/3)/pnorm(0,0,10/3))
            
            # to avoid data issue where non-unique household locations exits
            hhprobs[which(Distances[,temp_mozzy_hh_index]==0)]<-0
            
            #generate the next location
            cum_new_hh<-cumsum(hhprobs)
            temp_state<-hh_labels[which((runif(1)*cum_new_hh[length(cum_new_hh)])<cum_new_hh)[1]]
            
            #If the mosquito is no longer full it travels
          }else{
            temp_hh<-temp_state
            next_hh_index<-which(hh_labels==temp_state)
            temp_t<-temp_t+rexp(1,rate=flight_rate/(Distances[temp_mozzy_hh_index,next_hh_index]))
            temp_mozzy_hh_index<-next_hh_index
            temp_state<-1
            
          }
          
          #changes the mosquito to the infectious class (for purposes of assessing effective contact)
          if(temp_t>temp_infectious_time){
            temp_infectious_state<-1
          }
          
          # record the mozzies that are not infectious 
          if(temp_t<temp_death_time[m_count] & temp_t<max_t){
            stack_size<-stack_size+1
            mosquito_stack$mosquito_id[stack_size]<-mozzy_id
            mosquito_stack$hh_id[stack_size]<-temp_hh
            mosquito_stack$t[stack_size]<-temp_t
            mosquito_stack$event[stack_size]<-temp_state
            mosquito_stack$infectious_status[stack_size]<-temp_infectious_state
            mosquito_stack$mal_species[stack_size] <- temp_mal_species
          }
        }
        
        #if the mozzy didn't die from a natural bite and the next event would have occured before the end of the simulation period
        if(mosquito_stack$event[stack_size]!=3){ #& temp_death_time[m_count]<max_t){
          stack_size<-stack_size+1
          mosquito_stack$mosquito_id[stack_size]<-mozzy_id
          mosquito_stack$hh_id[stack_size]<-temp_hh
          mosquito_stack$t[stack_size]<-min(temp_death_time[m_count],max_t)
          mosquito_stack$event[stack_size]<-3
          mosquito_stack$infectious_status[stack_size]<-temp_infectious_state
          mosquito_stack$mal_species[stack_size] <- temp_mal_species
        }
        #propose new mosquito introduction from sick person zz
        t_delta<-mozzy_generation_times(t2,new_mozzys,t3)
      }
      
      }
      
      

  }
  






  # ordering the poss inf stack by time
  possible_infection_stack<-possible_infection_stack[order(possible_infection_stack$t),]
  if(sum(1*(!is.na(possible_infection_stack$t)))!=0){
    poss_inf_index<-which.min(possible_infection_stack$t)
    t<-possible_infection_stack$t[poss_inf_index]
  }else{
    t<-max_t+1
  }




  ## all events not spawned from initially sick puppies:--------------------------
  # FULL TRANSMISSION LOOP #
  

  while(sum(1*(!is.na(possible_infection_stack$t)))!=0 & t<max_t){ # iterate through all possible infection events

      
      #finds the index of the next possible infection event
      poss_inf_index<-which.min(possible_infection_stack$t)

      #find the relevant row in the data frame for the individual
      inf_row_num<-which(ind_level_data$hh_id==possible_infection_stack$hh_id[poss_inf_index] & ind_level_data$ind_id==possible_infection_stack$ind_id[poss_inf_index])
      
      #check events of the person on the stack (prior to the possible transmission event) -> gives row indices of human_stack
      person_events<-which(human_stack$df_index==inf_row_num & human_stack$t<possible_infection_stack$t[poss_inf_index])
      
      #get the species for the possible transmission event
      temp_mal_species <- possible_infection_stack$mal_species[poss_inf_index]
      if (temp_mal_species == 1){temp_other_mal_species <- 3} else {temp_other_mal_species <- 1}
       # to find occurrences of the other malaria species (for interactions)
      
      last_event <- human_stack[,paste(spec_names[temp_mal_species], "_state_current", sep = "")][which(human_stack$t == human_stack$t[person_events][which.max(human_stack$t[person_events])])]
      last_other_event <- human_stack[,paste(spec_names[temp_other_mal_species], "_state_current", sep = "")][which(human_stack$t == human_stack$t[person_events][which.max(human_stack$t[person_events])])]
      last_other_event_prev <- human_stack[,paste(spec_names[temp_other_mal_species], "_state_prev", sep = "")][which(human_stack$t == human_stack$t[person_events][which.max(human_stack$t[person_events])])]
      

      ## STATE TRANSITION 
      #if the person isn't on the stack they are susceptible
      if(length(person_events)==0 # if they aren't on the stack
         ){ 
        #add this infection to the stack
        add_to_stack<-TRUE
        t<-possible_infection_stack$t[poss_inf_index]
        
        # hand-coded version:
        temp_state_prev <- 0
        
        #if the person is on the stack, but their last event was a treatment event then they are susceptible at the time of the bite
       }else if(

        # if they are on the stack but last event was a recovery event
        # or all of their events were for the other malaria species if reinfection is turned on (not currently the case)
        
        last_event == 0 #| all(human_stack$mal_species_t[person_events] == temp_other_mal_species) # either one of these needs to be true
        
      ){
        add_to_stack<-TRUE
        t<-possible_infection_stack$t[poss_inf_index]

        # hand-coded version:
        temp_state_prev <- 0
        # alternative:
        # temp_state_prev <- human_stack[,paste(spec_names[temp_mal_species], "_state_current", sep = "")][which.max(human_stack$t[person_events])]
   
        
      }else{
        add_to_stack<-FALSE
      }
      
      # clear the current index entry
      possible_infection_stack[poss_inf_index,]<-NA
      
      
      
      
      if(add_to_stack){
        
      
        
        # if there are no events of the other malaria species on stack, assign them to be susceptible (0)
        if(length(last_other_event)==0 & length(last_other_event_prev)==0){ # they should always be either both or none NA
          last_other_event <- 0 # to be overwritten if needed in the next few lines
          last_other_event_prev <- 0
        }
        
        
        # if the species is vivax
        if(temp_mal_species == 3){ 
          h_stack_count<-h_stack_count+1
          temp_first_count <- h_stack_count # setting up the count for events per person per iteration
          
          ## exposure event on stack (just for plots)
          
          human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num]
          human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
          human_stack$df_index[h_stack_count]<-inf_row_num
          human_stack$t[h_stack_count]<-t
          human_stack$Pf_state_prev[h_stack_count]<-last_other_event
          human_stack$Pf_state_current[h_stack_count]<-last_other_event_prev
          human_stack$Pv_state_prev[h_stack_count]<-temp_state_prev
          human_stack$Pv_state_current[h_stack_count]<-1
          human_stack$mal_species_t[h_stack_count] <- temp_mal_species
          
          ## infectious event on stack
          h_stack_count<-h_stack_count+1
          human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num]
          human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
          human_stack$df_index[h_stack_count]<-inf_row_num
          human_stack$t[h_stack_count]<-t+rexp(1,rate=sigmaH)
          human_stack$Pf_state_prev[h_stack_count]<-human_stack$Pf_state_current[h_stack_count-1]
          human_stack$Pf_state_current[h_stack_count]<-human_stack$Pf_state_prev[h_stack_count] # no change in other species
          human_stack$Pv_state_prev[h_stack_count]<-human_stack$Pv_state_current[h_stack_count-1]
          human_stack$Pv_state_current[h_stack_count]<-2
          human_stack$mal_species_t[h_stack_count] <- temp_mal_species
          tI_in[h_stack_count]<-human_stack$t[h_stack_count]
          
          # to make less redundant: in vivax pathway: delete the redundant lines for the first next event
          # in falciparum it's already done
          # # general info for the next event:
          # h_stack_count<-h_stack_count+1
          # human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
          # human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
          # human_stack$df_index[h_stack_count]<-inf_row_num #
          # human_stack$mal_species_t[h_stack_count] <- temp_mal_species
          # 
          # human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
          # human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
          # human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
          
          # next events: (radical cure treatment, standard treatment, no treatment)
          rand_treat <- runif(1) # drawing a random number to decide whether the ind gets treated or not
          if(rand_treat < treat_prob){ # if they get treated
            rand_cure <- runif(1)
            if(rand_cure < cure_prob){ # if they get radical cure (prob for standard cure is 1-cure_prob)
              # record treatment (beginning of radical cure treatment)
              h_stack_count<-h_stack_count+1
              tI_out[h_stack_count]<- tI_in[h_stack_count-1]+rexp(1,rate=treat_speed) 
              human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
              tG[h_stack_count]<-human_stack$t[h_stack_count]
              human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
              human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
              human_stack$df_index[h_stack_count]<-inf_row_num #
              human_stack$mal_species_t[h_stack_count] <- temp_mal_species
              
              human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
              human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
              human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
              human_stack$Pv_state_current[h_stack_count]<- 4 # 4 is G
              
              
              # record loss of immunity (end of radical cure treatment)
              h_stack_count<-h_stack_count+1
              human_stack$t[h_stack_count] <- human_stack$t[h_stack_count-1] + dur_RC
              human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
              human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
              human_stack$df_index[h_stack_count]<-inf_row_num #
              human_stack$mal_species_t[h_stack_count] <- temp_mal_species
              
              human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
              human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
              human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
              human_stack$Pv_state_current[h_stack_count]<- 0 # 0 is S
              tS[h_stack_count]<-human_stack$t[h_stack_count]
              
            }else{ # standard cure
              # record treatment (beginning of standard cure treatment)
              h_stack_count<-h_stack_count+1
              tI_out[h_stack_count]<-tI_in[h_stack_count-1]+rexp(1,rate=treat_speed) 
              human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
              tT[h_stack_count]<-human_stack$t[h_stack_count]
              human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
              human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
              human_stack$df_index[h_stack_count]<-inf_row_num #
              human_stack$mal_species_t[h_stack_count] <- temp_mal_species
              
              human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
              human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
              human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
              human_stack$Pv_state_current[h_stack_count]<- 5 # 5 is T
              
              rand_LvT <- runif(1)
              if(rand_LvT < LvT_prob){ # if they develop hypnozoites after standard cure treatment
                # record latent event
                h_stack_count<-h_stack_count+1
                human_stack$t[h_stack_count] <- human_stack$t[h_stack_count-1] + dur_SC
                human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
                human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
                human_stack$df_index[h_stack_count]<-inf_row_num #
                human_stack$mal_species_t[h_stack_count] <- temp_mal_species
                
                human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
                human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
                human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
                human_stack$Pv_state_current[h_stack_count]<- 6 # 6 is L
                tL[h_stack_count]<-human_stack$t[h_stack_count]
                
                rand_rel<-runif(1)
                if (rand_rel < relapse_prob){
                  # repeat all pathways from infection event
                  # we're doing just one possible relapse
                  
                  
                  ## relapse infectious event on stack
                  h_stack_count<-h_stack_count+1
                  human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num]
                  human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
                  human_stack$df_index[h_stack_count]<-inf_row_num
                  human_stack$t[h_stack_count]<-t+rexp(1,rate=relapse_rate)
                  human_stack$Pf_state_prev[h_stack_count]<-human_stack$Pf_state_current[h_stack_count-1]
                  human_stack$Pf_state_current[h_stack_count]<-human_stack$Pf_state_prev[h_stack_count] # no change in other species
                  human_stack$Pv_state_prev[h_stack_count]<-human_stack$Pv_state_current[h_stack_count-1]
                  human_stack$Pv_state_current[h_stack_count]<-2
                  human_stack$mal_species_t[h_stack_count] <- temp_mal_species
                  tI_in[h_stack_count]<-human_stack$t[h_stack_count]
                  L_relapse_count<-L_relapse_count+1
                  
                  # next events: (radical cure treatment, standard treatment, no treatment)
                  rand_treat <- runif(1) # drawing a random number to decide whether the ind gets treated or not
                  if(rand_treat < treat_prob){ # if they get treated
                    rand_cure <- runif(1)
                    if(rand_cure < cure_prob){ # if they get radical cure (prob for standard cure is 1-cure_prob)
                      # record treatment (beginning of radical cure treatment)
                      h_stack_count<-h_stack_count+1
                      tI_out[h_stack_count]<- tI_in[h_stack_count-1]+rexp(1,rate=treat_speed) 
                      human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
                      tG[h_stack_count]<-human_stack$t[h_stack_count]
                      human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
                      human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
                      human_stack$df_index[h_stack_count]<-inf_row_num #
                      human_stack$mal_species_t[h_stack_count] <- temp_mal_species
                      
                      human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
                      human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
                      human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
                      human_stack$Pv_state_current[h_stack_count]<- 4 # 4 is G
                      
                      
                      # record loss of immunity (end of radical cure treatment)
                      h_stack_count<-h_stack_count+1
                      human_stack$t[h_stack_count] <- human_stack$t[h_stack_count-1] + dur_RC
                      human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
                      human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
                      human_stack$df_index[h_stack_count]<-inf_row_num #
                      human_stack$mal_species_t[h_stack_count] <- temp_mal_species
                      
                      human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
                      human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
                      human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
                      human_stack$Pv_state_current[h_stack_count]<- 0 # 0 is S
                      tS[h_stack_count]<-human_stack$t[h_stack_count]
                      
                    }else{ # standard cure
                      # record treatment (beginning of standard cure treatment)
                      h_stack_count<-h_stack_count+1
                      tI_out[h_stack_count]<-tI_in[h_stack_count-1]+rexp(1,rate=treat_speed) 
                      human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
                      tT[h_stack_count]<-human_stack$t[h_stack_count]
                      human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
                      human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
                      human_stack$df_index[h_stack_count]<-inf_row_num #
                      human_stack$mal_species_t[h_stack_count] <- temp_mal_species
                      
                      human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
                      human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
                      human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
                      human_stack$Pv_state_current[h_stack_count]<- 5 # 5 is T
                      
                      # we assume hypnozoites can only cause one relapse, so no new or remaining hypnozoites after relapse
                      
                      # record recovery
                      h_stack_count<-h_stack_count+1
                      human_stack$t[h_stack_count] <- human_stack$t[h_stack_count-1] + dur_SC
                      human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
                      human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
                      human_stack$df_index[h_stack_count]<-inf_row_num #
                      human_stack$mal_species_t[h_stack_count] <- temp_mal_species
                      
                      human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
                      human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
                      human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
                      human_stack$Pv_state_current[h_stack_count]<- 0 # 0 is S
                      tS[h_stack_count]<-human_stack$t[h_stack_count]
                      
                    }
                    
                  }else{ # no treatment
                    
                    #no hypnozoites after no treatment
                    # record recovery event without hypnozoites
                    h_stack_count<-h_stack_count+1
                    tI_out[h_stack_count]<-tI_in[h_stack_count-1]+rexp(1,rate=gammaH) # everybody who is already infectious will be treated by this time (defined by recovery rate gammaH)
                    human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
                    tS[h_stack_count]<-human_stack$t[h_stack_count]
                    human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
                    human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
                    human_stack$df_index[h_stack_count]<-inf_row_num #
                    human_stack$mal_species_t[h_stack_count] <- temp_mal_species
                    
                    human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
                    human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
                    human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
                    human_stack$Pv_state_current[h_stack_count]<- 0 # 0 is S
                    
                  }
                }else{# no relapse
                
                  # record recovery  (abbau von hynozoites)
                  h_stack_count<-h_stack_count+1
                  human_stack$t[h_stack_count] <- human_stack$t[h_stack_count-1] + rexp(1,rate=no_hypno)
                  human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
                  human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
                  human_stack$df_index[h_stack_count]<-inf_row_num #
                  human_stack$mal_species_t[h_stack_count] <- temp_mal_species
                  
                  human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
                  human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
                  human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
                  human_stack$Pv_state_current[h_stack_count]<- 0 # 0 is S
                  tS[h_stack_count]<-human_stack$t[h_stack_count]
              }
              }else{ # no hypnozoites after standard cure
                # record recovery
                h_stack_count<-h_stack_count+1
                human_stack$t[h_stack_count] <- human_stack$t[h_stack_count-1] + dur_SC
                human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
                human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
                human_stack$df_index[h_stack_count]<-inf_row_num #
                human_stack$mal_species_t[h_stack_count] <- temp_mal_species
                
                human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
                human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
                human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
                human_stack$Pv_state_current[h_stack_count]<- 0 # 0 is S
                tS[h_stack_count]<-human_stack$t[h_stack_count]
                
              }
            }
            
          }else{ # no treatment
            rand_Lv <- runif(1)
            if(rand_Lv < Lv_prob){ #hypnozoites after no treatment
              # record latent event
              h_stack_count<-h_stack_count+1
              tI_out[h_stack_count]<-tI_in[h_stack_count-1]+rexp(1,rate=Ldev_rate) 
              human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
              tL[h_stack_count]<-human_stack$t[h_stack_count]
              human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
              human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
              human_stack$df_index[h_stack_count]<-inf_row_num #
              human_stack$mal_species_t[h_stack_count] <- temp_mal_species
              
              human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
              human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
              human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
              human_stack$Pv_state_current[h_stack_count]<- 6 # 6 is L
              
              rand_rel<-runif(1)
              if (rand_rel < relapse_prob){
                # repeat all pathways from infection event
                # we#re doing just one possible relapse
                
                
                ## relapse infectious event on stack
                h_stack_count<-h_stack_count+1
                human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num]
                human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
                human_stack$df_index[h_stack_count]<-inf_row_num
                human_stack$t[h_stack_count]<-t+rexp(1,rate=relapse_rate)
                human_stack$Pf_state_prev[h_stack_count]<-human_stack$Pf_state_current[h_stack_count-1]
                human_stack$Pf_state_current[h_stack_count]<-human_stack$Pf_state_prev[h_stack_count] # no change in other species
                human_stack$Pv_state_prev[h_stack_count]<-human_stack$Pv_state_current[h_stack_count-1]
                human_stack$Pv_state_current[h_stack_count]<-2
                human_stack$mal_species_t[h_stack_count] <- temp_mal_species
                tI_in[h_stack_count]<-human_stack$t[h_stack_count]
                L_relapse_count<-L_relapse_count+1
                
                # next events: (radical cure treatment, standard treatment, no treatment)
                rand_treat <- runif(1) # drawing a random number to decide whether the ind gets treated or not
                if(rand_treat < treat_prob){ # if they get treated
                  rand_cure <- runif(1)
                  if(rand_cure < cure_prob){ # if they get radical cure (prob for standard cure is 1-cure_prob)
                    # record treatment (beginning of radical cure treatment)
                    h_stack_count<-h_stack_count+1
                    tI_out[h_stack_count]<- tI_in[h_stack_count-1]+rexp(1,rate=treat_speed) 
                    human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
                    tG[h_stack_count]<-human_stack$t[h_stack_count]
                    human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
                    human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
                    human_stack$df_index[h_stack_count]<-inf_row_num #
                    human_stack$mal_species_t[h_stack_count] <- temp_mal_species
                    
                    human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
                    human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
                    human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
                    human_stack$Pv_state_current[h_stack_count]<- 4 # 4 is G
                    
                    
                    # record loss of immunity (end of radical cure treatment)
                    h_stack_count<-h_stack_count+1
                    human_stack$t[h_stack_count] <- human_stack$t[h_stack_count-1] + dur_RC
                    human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
                    human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
                    human_stack$df_index[h_stack_count]<-inf_row_num #
                    human_stack$mal_species_t[h_stack_count] <- temp_mal_species
                    
                    human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
                    human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
                    human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
                    human_stack$Pv_state_current[h_stack_count]<- 0 # 0 is S
                    tS[h_stack_count]<-human_stack$t[h_stack_count]
                    
                  }else{ # standard cure
                    # record treatment (beginning of standard cure treatment)
                    h_stack_count<-h_stack_count+1
                    tI_out[h_stack_count]<-tI_in[h_stack_count-1]+rexp(1,rate=treat_speed) 
                    human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
                    tT[h_stack_count]<-human_stack$t[h_stack_count]
                    human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
                    human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
                    human_stack$df_index[h_stack_count]<-inf_row_num #
                    human_stack$mal_species_t[h_stack_count] <- temp_mal_species
                    
                    human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
                    human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
                    human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
                    human_stack$Pv_state_current[h_stack_count]<- 5 # 5 is T
                    
                    # we assume hypnozoites can only cause one relapse, so no new or remaining hypnozoites after relapse
                    
                    # record recovery
                    h_stack_count<-h_stack_count+1
                    human_stack$t[h_stack_count] <- human_stack$t[h_stack_count-1] + dur_SC
                    human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
                    human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
                    human_stack$df_index[h_stack_count]<-inf_row_num #
                    human_stack$mal_species_t[h_stack_count] <- temp_mal_species
                    
                    human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
                    human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
                    human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
                    human_stack$Pv_state_current[h_stack_count]<- 0 # 0 is S
                    tS[h_stack_count]<-human_stack$t[h_stack_count]
                    
                  }
                  
                }else{ # no treatment
                  
                  #no hypnozoites after no treatment
                  # record recovery event without hypnozoites
                  h_stack_count<-h_stack_count+1
                  tI_out[h_stack_count]<-tI_in[h_stack_count-1]+rexp(1,rate=gammaH) # everybody who is already infectious will be treated by this time (defined by recovery rate gammaH)
                  human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
                  tS[h_stack_count]<-human_stack$t[h_stack_count]
                  human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
                  human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
                  human_stack$df_index[h_stack_count]<-inf_row_num #
                  human_stack$mal_species_t[h_stack_count] <- temp_mal_species
                  
                  human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
                  human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
                  human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
                  human_stack$Pv_state_current[h_stack_count]<- 0 # 0 is S
                  
                }
              }else{# no relapse
              
                # record recovery (decay von hynozoites)
                h_stack_count<-h_stack_count+1
                human_stack$t[h_stack_count] <- human_stack$t[h_stack_count-1] + rexp(1,rate=no_hypno)
                human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
                human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
                human_stack$df_index[h_stack_count]<-inf_row_num #
                human_stack$mal_species_t[h_stack_count] <- temp_mal_species
                
                human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
                human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
                human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
                human_stack$Pv_state_current[h_stack_count]<- 0 # 0 is S
                tS[h_stack_count]<-human_stack$t[h_stack_count]
              }
            }else{ #no hypnozoites after no treatment
              # record recovery event without hypnozoites
              h_stack_count<-h_stack_count+1
              tI_out[h_stack_count]<-tI_in[h_stack_count-1]+rexp(1,rate=gammaH) # everybody who is already infectious will be treated by this time (defined by recovery rate gammaH)
              human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
              tS[h_stack_count]<-human_stack$t[h_stack_count]
              human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
              human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
              human_stack$df_index[h_stack_count]<-inf_row_num #
              human_stack$mal_species_t[h_stack_count] <- temp_mal_species
              
              human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
              human_stack$Pf_state_current[h_stack_count]<- human_stack$Pf_state_prev[h_stack_count] # no change in Pf
              human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
              human_stack$Pv_state_current[h_stack_count]<- 0 # 0 is S
              
            }
          }
          
          
        }else{ # if not vivax (i.e. if falciparum)
          h_stack_count<-h_stack_count+1
          temp_first_count <- h_stack_count # setting up the count for events per person per iteration
          
          ## exposure event on stack (just for plots)
          
          human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num]
          human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
          human_stack$df_index[h_stack_count]<-inf_row_num
          human_stack$t[h_stack_count]<-t
          human_stack$Pv_state_prev[h_stack_count]<-last_other_event
          human_stack$Pv_state_current[h_stack_count]<-last_other_event_prev
          human_stack$Pf_state_prev[h_stack_count]<-temp_state_prev
          human_stack$Pf_state_current[h_stack_count]<-1
          human_stack$mal_species_t[h_stack_count] <- temp_mal_species
          
          ## infectious event on stack
          h_stack_count<-h_stack_count+1
          human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num]
          human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
          human_stack$df_index[h_stack_count]<-inf_row_num
          human_stack$t[h_stack_count]<-t+rexp(1,rate=sigmaH)
          human_stack$Pv_state_prev[h_stack_count]<-human_stack$Pv_state_current[h_stack_count-1]
          human_stack$Pv_state_current[h_stack_count]<-human_stack$Pv_state_prev[h_stack_count] # no change in other species
          human_stack$Pf_state_prev[h_stack_count]<-human_stack$Pf_state_current[h_stack_count-1]
          human_stack$Pf_state_current[h_stack_count]<-2
          human_stack$mal_species_t[h_stack_count] <- temp_mal_species
          tI_in[h_stack_count]<-human_stack$t[h_stack_count]
          
          # general info for the next event:
          h_stack_count<-h_stack_count+1
          human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
          human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
          human_stack$df_index[h_stack_count]<-inf_row_num #
          human_stack$mal_species_t[h_stack_count] <- temp_mal_species
          
          human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
          human_stack$Pv_state_current[h_stack_count]<- human_stack$Pv_state_prev[h_stack_count] # no change in Pv unless in radical cure, which is specified below and simply overwrites this line
          human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
          
          # next events: (radical cure treatment, standard treatment, no treatment)
          rand_treat <- runif(1) # drawing a random number to decide whether the ind gets treated or not
          if(rand_treat < treat_prob){ # if they get treated
            rand_cure <- runif(1)
            if(rand_cure < cure_prob){ # if they get radical cure (prob for standard cure is 1-cure_prob)
              # record treatment (beginning of radical cure treatment)
              tI_out[h_stack_count]<-tI_in[h_stack_count-1]+rexp(1,rate=treat_speed) 
              human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
              tG[h_stack_count]<-human_stack$t[h_stack_count]
              human_stack$Pf_state_current[h_stack_count]<- 4 # 4 is G
              human_stack$Pv_state_current[h_stack_count]<- 4 # radical cure acts on both species 
              # (hereby providing both temporary immunity for the duration of treatment and
              # clearing of liver-stage hypnozoites)
              
              # record loss of immunity (end of radical cure treatment)
              h_stack_count<-h_stack_count+1
              human_stack$t[h_stack_count] <- human_stack$t[h_stack_count-1] + dur_RC
              human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
              human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
              human_stack$df_index[h_stack_count]<-inf_row_num #
              human_stack$mal_species_t[h_stack_count] <- temp_mal_species
              
              human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
              human_stack$Pv_state_current[h_stack_count]<- 0 # 0 is S
              human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
              human_stack$Pf_state_current[h_stack_count]<- 0 # 0 is S
              tS[h_stack_count]<-human_stack$t[h_stack_count]
              
            }else{ # standard cure
              # record treatment (beginning of standard cure treatment)
              tI_out[h_stack_count]<-tI_in[h_stack_count-1]+rexp(1,rate=treat_speed) 
              human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
              tT[h_stack_count]<-human_stack$t[h_stack_count]
              human_stack$Pf_state_current[h_stack_count]<- 5 # 5 is T
              
              # record recovery/loss of immunity (end of standard cure treatment)
              h_stack_count<-h_stack_count+1
              human_stack$t[h_stack_count] <- human_stack$t[h_stack_count-1] + dur_SC
              human_stack$hh_id[h_stack_count]<-ind_level_data$hh_id[inf_row_num] # updating household ID to the household ID of the current sick person
              human_stack$ind_id[h_stack_count]<-ind_level_data$ind_id[inf_row_num]
              human_stack$df_index[h_stack_count]<-inf_row_num #
              human_stack$mal_species_t[h_stack_count] <- temp_mal_species
              
              human_stack$Pv_state_prev[h_stack_count]<- human_stack$Pv_state_current[h_stack_count-1]
              human_stack$Pv_state_current[h_stack_count]<- human_stack$Pv_state_prev[h_stack_count] # no change in Pv
              human_stack$Pf_state_prev[h_stack_count]<- human_stack$Pf_state_current[h_stack_count-1]
              human_stack$Pf_state_current[h_stack_count]<- 0 # 0 is S
              tS[h_stack_count]<-human_stack$t[h_stack_count]
              
            }
          }else{ # no treatment
            tI_out[h_stack_count]<-tI_in[h_stack_count-1]+rexp(1,rate=gammaH) # everybody who is already infectious will be treated by this time (defined by recovery rate gammaH)
            human_stack$t[h_stack_count]<-tI_out[h_stack_count] 
            tS[h_stack_count]<-human_stack$t[h_stack_count]
            human_stack$Pf_state_current[h_stack_count]<- 0 # 0 is S
          }
        }
        
        
        

         new_mozzys<-seasonal_creation[inf_row_num,] # seasonally varied creation rate of new mozzies
        
        #generate all mosquitos from the existing sick people
         
         temp_ind_tI <- as.data.frame(cbind( 
                                            na.omit(tI_in[temp_first_count:h_stack_count]),
                                            na.omit(tI_out[temp_first_count:h_stack_count])))
         
        for (kk in 1:nrow(temp_ind_tI)) {
           t2<-temp_ind_tI[kk, 2]
           t3<-temp_ind_tI[kk, 3]
          t_delta<-mozzy_generation_times(t2,new_mozzys,t3)
          while((t2+t_delta)<min(t3,max_t)){ #the mozzies can only be generated if the time is before the recovery/latency state or max t
            #generate/record time of event
            
            t2<-t2+t_delta
            
            #generate a mosquito into the relevant household
            ind_moz_index<-inf_row_num
            
            # Malaria mosquito activity is independent of the state of the system, 
            # assuming a fixed treatment of households over their
            # lifetime (the impact on infection is state dependent though)
            m_count<-m_count+1
            
            #currently let all mosquitoes be introduced as full (maybe change this later). 
            # 1: hungry, 2: full, 3: dead, hh_id: travelling to hh_id
            
            # now to add the mosquitoes movements to the stack
            # THESE CAN BE CHANGED TO NOT BE EXPONENTIAL
            temp_infectious_time<-t2+rexp(1,rate=sigmaM)
            exposure_time[m_count]<-temp_infectious_time
            temp_death_time[m_count]<-t2+rexp(1,rate=death_rate)
            
            
            mozzy_id<-m_count
            temp_hh<-ind_level_data$hh_id[ind_moz_index]
            temp_mozzy_hh_index<-which(hh_labels==temp_hh)
            temp_t<-t2
            temp_state<-2 ###THIS COULD BE CHANGED LATER
            temp_infectious_state<-0
            # temp_mal_species <- temp_mal_species # mal species is taken from the current human 
            
            stack_size<-stack_size+1
            mosquito_stack$mosquito_id[stack_size]<-mozzy_id
            mosquito_stack$hh_id[stack_size]<-temp_hh
            mosquito_stack$t[stack_size]<-temp_t
            mosquito_stack$event[stack_size]<-temp_state
            mosquito_stack$infectious_status[stack_size]<-temp_infectious_state
            mosquito_stack$mal_species[stack_size] <- temp_mal_species
            
            while(temp_t<temp_death_time[m_count] & temp_state!=3 & temp_t<max_t){
              
              #If the mosquito is hungry it bites
              if(temp_state==1){
                # if hungry bite and stay hungry, bite and get full or bite+die
                temp_t<-temp_t+rexp(1,rate=bite_rate)
                rand_event=runif(1)
                if(rand_event<multiple_meal){
                  #bite and not full
                  temp_state<-1
                }else if(rand_event<(multiple_meal+(1-multiple_meal)*(1-hh_deathonbite[temp_mozzy_hh_index]))){
                  #full
                  temp_state<-2
                }else{
                  #dead on bite
                  temp_state<-3
                }
                
                #generates effective contact between an infectious mosquito and a human
                if(temp_t>temp_infectious_time & temp_t<temp_death_time[m_count] & temp_t<max_t){
                  rand_inf=runif(1)
                  if(rand_inf<transMH_per_bite){ 
                    inf_stack_size<-inf_stack_size+1
                    possible_infection_stack$hh_id[inf_stack_size]<-temp_hh
                    possible_infection_stack$t[inf_stack_size]<-temp_t
                    possible_infection_stack$ind_id[inf_stack_size]<-ceiling(runif(1)*N[temp_mozzy_hh_index])
                    possible_infection_stack$mal_species[inf_stack_size] <- temp_mal_species
                  }
                }
                
                #If the mosquito is full it moves after a holding time
              }else if(temp_state==2){
                
                #generate time that the mosquito will be ready to travel
                temp_t<-temp_t+rexp(1,rate=Mfull)
                
                #the mosquitos choice of new hh
                the_season<-mydates$month[ current_daymonth(temp_t)]
                
                hhprobs<-(scaled_seasonal_MAP[,the_season]*hh_bite_prop)*(pnorm(Distances[,temp_mozzy_hh_index],0,10/3)/pnorm(0,0,10/3))
      
                #some data issue where non-unique household locations exits (check this)
                hhprobs[which(Distances[,temp_mozzy_hh_index]==0)]<-0
                
                #generate the next location
                cum_new_hh<-cumsum(hhprobs)
                temp_state<-hh_labels[which((runif(1)*cum_new_hh[length(cum_new_hh)])<cum_new_hh)[1]]

                #If the mosquito is no longer full it travels
              }else{
                temp_hh<-temp_state
                next_hh_index<-which(hh_labels==temp_state)
                temp_t<-temp_t+rexp(1,rate=flight_rate/(Distances[temp_mozzy_hh_index,next_hh_index]))
                temp_mozzy_hh_index<-next_hh_index
                temp_state<-1
                
              }
              
              #changes the mosquito to the infectious class (for purposes of assessing effective contact)
              if(temp_t>temp_infectious_time){
                temp_infectious_state<-1
              }
              
              if(temp_t<temp_death_time[m_count] & temp_t<max_t){
                stack_size<-stack_size+1
                mosquito_stack$mosquito_id[stack_size]<-mozzy_id
                mosquito_stack$hh_id[stack_size]<-temp_hh
                mosquito_stack$t[stack_size]<-temp_t
                mosquito_stack$event[stack_size]<-temp_state
                mosquito_stack$infectious_status[stack_size]<-temp_infectious_state
                mosquito_stack$mal_species[stack_size] <- temp_mal_species
              }
            }
            
            #if the mozzy didn't die from a natural bite and the next event would have occured before the end of the simulation period
            if(mosquito_stack$event[stack_size]!=3){# & temp_death_time<max_t){
              stack_size<-stack_size+1
              mosquito_stack$mosquito_id[stack_size]<-mozzy_id
              mosquito_stack$hh_id[stack_size]<-temp_hh
              mosquito_stack$t[stack_size]<-min(temp_death_time[m_count],max_t)
              mosquito_stack$event[stack_size]<-3
              mosquito_stack$infectious_status[stack_size]<-temp_infectious_state
              mosquito_stack$mal_species[stack_size] <- temp_mal_species
            }
            #propose new mosquito introduction from sick person zz
            t_delta<-mozzy_generation_times(t2,new_mozzys,t3)
          }
        }
        
        
        
      }  
    }
  